import { useState, useEffect } from 'react'
import usePageMeta from '../hooks/usePageMeta'
import dimensions from '../gallery/thumbs.json'
import { examples } from '../data/examples'

const fileKey = (path) => path.split('/').pop().replace(/\.[^.]+$/, '')

// Downscaled grid thumbnails, generated by scripts/gen-thumbs.mjs.
const thumbs = Object.fromEntries(
  Object.entries(import.meta.glob('../gallery/thumbs/*.webp', { eager: true })).map(
    ([path, mod]) => [fileKey(path), mod.default]
  )
)

const allImages = Object.entries(
  import.meta.glob('../gallery/*.{jpg,jpeg,png,gif,webp,svg,avif,PNG,JPG,JPEG,WEBP}', { eager: true })
).map(([path, mod]) => ({
  src: mod.default,
  key: fileKey(path),
  name: fileKey(path).replace(/[-_]/g, ' '),
  ext: path.split('.').pop().toLowerCase(),
}))

const imageMap = new Map()
for (const img of allImages) {
  const existing = imageMap.get(img.name)
  if (!existing || img.ext === 'webp') {
    imageMap.set(img.name, img)
  }
}
const images = [...imageMap.values()].map((img) => ({
  ...img,
  thumb: thumbs[img.key] || img.src,
  ...(dimensions[img.key] || {}),
}))

// Screenshots of community timelines, kept out of the grid glob above.
const exampleShots = Object.fromEntries(
  Object.entries(import.meta.glob('../gallery/examples/*.webp', { eager: true })).map(
    ([path, mod]) => [fileKey(path), mod.default]
  )
)

const hostLabel = (url) => new URL(url).hostname.replace(/^www\./, '')

function Gallery() {
  usePageMeta({
    title: 'Gallery',
    description: 'Screenshots and visuals from Timelines, plus timelines published by the community.',
  })

  const [selectedIndex, setSelectedIndex] = useState(null)

  const prev = () => setSelectedIndex((i) => (i - 1 + images.length) % images.length)
  const next = () => setSelectedIndex((i) => (i + 1) % images.length)

  useEffect(() => {
    if (selectedIndex === null) return
    const onKey = (e) => {
      if (e.key === 'Escape') setSelectedIndex(null)
      if (e.key === 'ArrowLeft') prev()
      if (e.key === 'ArrowRight') next()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [selectedIndex])

  const selected = selectedIndex !== null ? images[selectedIndex] : null

  return (
    <div className="page gallery">
      <h1 className="page-title">Gallery</h1>
      <p className="page-subtitle">Screenshots and visuals from Timelines.</p>

      {images.length === 0 ? (
        <p className="gallery-empty">No images yet.</p>
      ) : (
        <div className="gallery-grid">
          {images.map((img, i) => (
            <button key={i} className="gallery-item" onClick={() => setSelectedIndex(i)}>
              <img
                src={img.thumb}
                alt={img.name}
                width={img.width}
                height={img.height}
                loading="lazy"
                decoding="async"
              />
            </button>
          ))}
        </div>
      )}

      {selected && (
        <div className="gallery-lightbox" onClick={() => setSelectedIndex(null)}>
          <button className="gallery-nav gallery-nav-prev" onClick={(e) => { e.stopPropagation(); prev() }}>&#8249;</button>
          <img
            key={selected.src}
            src={selected.src}
            alt={selected.name}
            width={selected.width}
            height={selected.height}
            style={{ backgroundImage: `url(${selected.thumb})` }}
            onClick={(e) => e.stopPropagation()}
          />
          <button className="gallery-nav gallery-nav-next" onClick={(e) => { e.stopPropagation(); next() }}>&#8250;</button>
        </div>
      )}

      {examples.length > 0 && (
        <section className="gallery-examples">
          <h2 className="gallery-examples-title">Made with Timelines</h2>
          <p className="gallery-examples-subtitle">
            Public timelines built by the community and published on the web.
          </p>
          <div className="gallery-examples-grid">
            {examples.map((example) => (
              <a
                key={example.url}
                className="gallery-example"
                href={example.url}
                target="_blank"
                rel="noopener noreferrer"
              >
                {exampleShots[example.image] && (
                  <img
                    className="gallery-example-shot"
                    src={exampleShots[example.image]}
                    alt={`${example.name} screenshot`}
                    width="1600"
                    height="1000"
                    loading="lazy"
                    decoding="async"
                  />
                )}
                <div className="gallery-example-body">
                  <h3>{example.name}</h3>
                  <p>{example.description}</p>
                  <span className="gallery-example-link">
                    {hostLabel(example.url)} <span aria-hidden="true">&rarr;</span>
                  </span>
                </div>
              </a>
            ))}
          </div>
        </section>
      )}

      <div className="survey-callout">
        <p>Help shape the future of Timelines. Takes under 2 minutes.</p>
        <a href="https://forms.gle/Bbe74yyrZ7zhKeFL8" className="btn btn-primary survey-callout-btn" target="_blank" rel="noopener noreferrer">
          Take the Survey <span aria-hidden="true">&rarr;</span>
        </a>
      </div>
    </div>
  )
}

export default Gallery
